server:
  port: 80
    
spring:
  thymeleaf:
    encoding: utf-8
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  devtools:
    restart:
      enabled: true
  servlet:    multipart:      enabled: true
      max-file-size: 1024MB
      
      
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mybatis/**/*Mapper.xml
  typeAliasesPackage: com.mustr.**.entity
  
pagehelper:
  helper-dialect: mysql
 
management:
  endpoints:
    web:
      exposure:
        include: ['httptrace', 'metrics']
  