server:
  port: 80
    
spring:
  thymeleaf:
    encoding: utf-8
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  devtools:
    restart:
      enabled: true
  servlet:    multipart:      enabled: true
      max-request-size: 1024MB    #总数据大小
      max-file-size: 1024MB    #可上传的文件大小
      
      
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mybatis/**/*Mapper.xml
  typeAliasesPackage: com.mustr.**.entity
  
pagehelper:
  helper-dialect: mysql
 
mustr:  minio:    endpoint: http://192.168.1.63:9000  #minio路径，http://不能少
    access-key: dascomsoft
    secret-key: dascomsoft
    bucket: boot-mustr
 
management:
  endpoints:
    web:
      exposure:
        include: ['httptrace', 'metrics']
        
jodconverter:
    #local:
    #    enabled: true
    #    officeHome: /opt/libreoffice6.4
    #    taskExecutionTimeout: 600000  #任务执行的时长，超过这个时间之间终止转换
    remote:
        enabled: true
        url: http://192.168.1.65:9980  #liberoffice online的地址
        taskExecutionTimeout: 600000  #任务执行的时长，超过这个时间之间终止转换
  